#!/usr/bin/env python

import pandas as pd
import os
import glob


path = os.getcwd()
files=glob.glob(os.path.join(path, "*.csv"))
WT_Read_Col_List =["Extension","Files"]

WizTree = 'Generated by WizTree 4.07 08/02/2022 01:57:17 (You can hide this message by making a donation)'


#test if LODOS or WizTree

#remove all headers WizTree



#read csvs with matching columns in files dir
new_csv = pd.concat([pd.read_csv(f,usecols=(WT_Read_Col_List),skiprows=(1)) for f in files])

# #change column names
new_csv.columns = ["Extension", "Allocated Filesize GB"]

# #divide to GB, add *1024 for TB
new_csv["Allocated Filesize GB"] = [x/(1024*1024*1024) for x in new_csv["Allocated Filesize GB"]]

# #sum of identical values
new_csv["Allocated Filesize GB"] = new_csv.groupby(["Extension"])["Allocated Filesize GB"].transform('sum')

# #drop duplicates
new_csv.drop_duplicates(subset = "Extension", keep = 'first', inplace = True)

# #sort descending
new_csv = new_csv.sort_values(by='Allocated Filesize GB', ascending = False)

# #show  files above 20GB and write to new csv
new_csv[new_csv["Allocated Filesize GB"] > 20].to_csv( "new_csv.csv", index=False, encoding='utf-8-sig')


